entity.3001 = minecraft:glow_squid minecraft:allay minecraft:blaze minecraft:magma_cube
entity.3002 = minecraft:enderman minecraft:endermite minecraft:ender_dragon minecraft:shulker
entity.3003 = minecraft:lightning_bolt
