# Item classes reserved for future per-item lighting extensions.
item.2001 = minecraft:torch minecraft:lantern minecraft:glowstone minecraft:shroomlight minecraft:ochre_froglight minecraft:pearlescent_froglight minecraft:verdant_froglight
item.2002 = minecraft:soul_torch minecraft:soul_lantern minecraft:sea_lantern minecraft:end_rod
item.2003 = minecraft:lava_bucket minecraft:magma_block
